### ISSUE TITLE
Receive a 401: Unauthorized error when trying to log in

### ISSUE THREAD

**Issue by agquinn01** [jlooper/storytelling-app#19]
I get this error for logging in with Google, Twitter, and Facebook. 

Error takes me here: https://yellow-stone-01866870f.azurestaticapps.net/.auth/login/twitter?post_login_redirect_uri=/admin/home

**Comment by jlooper** [comment]
Looks like this is a browser issue. For demos, we are recommending Safari or Firefox. Let's rely on those!

**Comment by jlooper** [comment]
Just got word this is fixed, let's test!

**Comment by agquinn01** [comment]
It's working in Chrome! Thanks!
